### ISSUE TITLE
Keep running into error- AttributeError: 'list' object has no attribute 'replace'

### ISSUE THREAD

**Issue by hab33bi** [reteps/quizizz-bot#5]
here's the log

```
Enable Delay? >>>n
[info] Starting game
[Info] Retrieving QuidID
Found: 5aed7e174ed324001bd45cc6
You can visit https://quizizz.com/quiz/5aed7e174ed324001bd45cc6 for answer. (You will need a quizizz account)
Traceback (most recent call last):
  File "/Users/habeeb/Downloads/quizizz-bot-37a6c521052c876377e431b673f337b350499459/quizizz-bot.py", line 161, in <module>
    play(input("PIN >>> "), input("username >>> "), input("Enable Delay? >>>")) 
  File "/Users/habeeb/Downloads/quizizz-bot-37a6c521052c876377e431b673f337b350499459/quizizz-bot.py", line 92, in play
    answers = find_answers(GameID)
  File "/Users/habeeb/Downloads/quizizz-bot-37a6c521052c876377e431b673f337b350499459/quizizz-bot.py", line 44, in find_answers
    answers[questionID.replace("&nbsp;"," ").replace(u'\xa0',u' ').rstrip().lower()] = answer.replace("&nbsp;"," ").rstrip().lower()
AttributeError: 'list' object has no attribute 'replace'
```

**Comment by LostQuasar** [comment]
What version of python, also did you install requests and selenium

**Comment by hab33bi** [comment]
> What version of python, also did you install requests and selenium

I'm using python3.7.2 and I'm pretty sure i've installed them

**Comment by hab33bi** [comment]
> What version of python, also did you install requests and selenium

I've just installed python 3.7.3 and it's still not working, I believe selenium and requests are installed. i installed them via pip3 install

**Comment by Skyluro** [comment]
could you send me the quiz you are trying to complete?

**Comment by Skyluro** [comment]
Ok, so this is something specific to that quiz. I think it's just that there is nothing in the list to replace but not too sure yet. I will look into it tomorrow. If you have a deadline you have to meet use this link to answer it manually.

https://quizizz.com/admin/quiz/5aed7e174ed324001bd45cc6/aqa-computer-science-giant-quizizz-paper-1

**Comment by hab33bi** [comment]
> Ok, so this is something specific to that quiz. I think it's just that there is nothing in the list to replace but not too sure yet. I will look into it tomorrow. If you have a deadline you have to meet use this link to answer it manually.
> 
> https://quizizz.com/admin/quiz/5aed7e174ed324001bd45cc6/aqa-computer-science-giant-quizizz-paper-1

Having the answers is not what I want to be able to do here. I want to be able to have the answers automatically filled as I want top leaderboard. Please help me!

**Comment by reteps** [comment]
I would reccommend transititioning to https://github.com/idiidk/kahoot-tools for now. I do not have time rn to maintain this.

**Comment by Skyluro** [comment]
Ok, so it works now but it will get at most 2 questions wrong for **your particular quiz** because there are two questions with the same text. I would fix this (add a thing to try to search by image or answers in a case where 2 or more questions have the same text) however, I still have homework to do and tbh I started debugging today around 4 so yea(tired). Look in my repo for code.
